[tool.poetry]
name = "GANs"
version = "0.1.0"
description = ""
authors = ["haceneterbouche <hacene@powder.gg>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.8.1" # +cu111
torchvision = "^0.9.1" # +cu111
torchaudio = "^0.8.1"
pytorch-lightning = "1.3.8"
poethepoet = "^0.10.0"
sklearn = "^0.0"
pandas = "^1.2.4"
comet-ml = "^3.9.1"
matplotlib = "^3.5.1"



[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.16.0"
ipykernel = "^6.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks]
force-cuda11 = "python -m pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html"


[tool.black]
# Black formatter configuration
line-length = 89
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.sublime-workspace
  | .idea
  | .venv
  | .vscode
  | _build
  | buck-out
  | build
  | dist
)/
'''
